#pragma config(Sensor, dgtl1,  Sonar_input,    sensorSONAR_inch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int sonar_value = SensorValue(Sonar_input);
task main()
{

	if (sonar_value < 3)
		{
			//some weird program will be going here (:
		}


}


task autonomous ()
{
}
