#pragma config(Sensor, in1,    leftWing,       sensorPotentiometer)
#pragma config(Sensor, dgtl1,  startSonar,     sensorSONAR_mm)
#pragma config(Sensor, dgtl3,  power,          sensorNone)
#pragma config(Sensor, dgtl4,  ground,         sensorNone)
#pragma config(Motor,  port2,           leftWing,      tmotorVex269_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           Center,        tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port6,           head,          tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port9,           rightWing,     tmotorVex269_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void rightNeck ()//.2
{
	setMotor(port6, -20);
	wait(.2);
	stopAllMotors();
}
void leftNeck ()//.2
{
	setMotor(port6, 20);
	wait(.2);
	stopAllMotors();
}
//* Code block to move wings (up, down, open and close)
void openWing ()//1
{
	setMotor(port2, 50);
	setMotor(port9, 50);
	wait(1);
	stopAllMotors();

}
void openRightWing()//1
{
	setMotor(port9, 50);
	wait(1);
	stopAllMotors();
}
void openLeftWing()//1
{
	setMotor(port2, 50);
	wait(1);
	stopAllMotors();
}
void closeWing ()
{
	setMotor(port2, -50);
	setMotor(port9, -50);
	wait(1);
	stopAllMotors();
}
void closeRightWing()//1
{
	setMotor(port9, -50);
	wait(1);
	stopAllMotors();
}
void closeLeftWing()//1
{
	setMotor(port2, -50);
	wait(1);
	stopAllMotors();
}
void upWing ()//4
{
	setMotor(port5, 127);
	wait(4);
	stopAllMotors();
}
void downWing ()//4
{
	setMotor(port5, -127);
	wait(4);
	stopAllMotors();
}



//* Code block for actual animatronic
//1:20
void autonomous ()
{
	leftNeck();//.2
	leftNeck();
	leftNeck();
	leftNeck();
	wait(1);
	rightNeck();//.2
	rightNeck();
	openWing ();//1
	upWing();//4
	wait(2);//3
	downWing();//4
	leftNeck ();//.2
	leftNeck ();//.2
	wait(3);//3
	closeWing ();//1
	rightNeck();//.2
	openRightWing();//1
	leftNeck ();//.2
	leftNeck();//.2
	openLeftWing();//1
	rightNeck();//.2
	rightNeck();//.2
	closeWing ();//1
	wait(3);//3
	//23.8
	rightNeck();//.2
	openRightWing();//1
	closeRightWing();//1
	openRightWing();//1
	leftNeck();//.2
	closeRightWing();//1
	wait(3);//3
	leftNeck();//.2
	openLeftWing();//1
	closeLeftWing();//1
	openLeftWing();//1
	rightNeck();//.2
	closeLeftWing();//1
	wait(3);//3
	//38.6
	rightNeck();//.2
	openWing();//1
	closeWing();//1
	openWing();//1
	closeWing();//1
	leftNeck();//.2
	leftNeck();//.2
	openWing();//1
	closeWing();//1
	openWing();//1
	//46.2
	wait(3);
	rightNeck();//.2
	openWing ();//1
	upWing();//4
	wait(3);//3
	downWing();//4
	leftNeck ();//.2
	leftNeck ();//.2
	wait(3);//3
	closeWing ();//1
	rightNeck();//.2
	openRightWing();//1
	leftNeck ();//.2
	leftNeck();//.2
	openLeftWing();//1
	rightNeck();//.2
	rightNeck();//.2
	closeWing ();//1
	wait(3);//3
	//1.12.8
	openWing();//1
	closeWing();//1
	openWing();//1
	closeWing();//1
	rightNeck();
	rightNeck();
	rightNeck();
	//1.17
}


//* Code block to start entire program
task main()
{
	while (1==1)
	{
		if (SensorValue[in1] == 0)
		{
			autonomous ();
		}
	}
}
