#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  intLEncoder,    sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  intREncoder,    sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           leftBMotor,    tmotorVex393_MC29, openLoop, driveLeft, encoderPort, I2C_1)
#pragma config(Motor,  port3,           leftFMotor,    tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port4,           leftLaunch,    tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port5,           intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Hopper,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           rightLaunch,   tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port8,           rightFMotor,   tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port9,           rightBMotor,   tmotorVex393_MC29, openLoop, reversed, driveRight, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

while (true)
{

			motor[port5] = vexRT[Ch3]; // The left joystick controls the left front motor

			motor[port5] = vexRT[Ch3]; // The left joystick controls the left back motor

			motor[port6] = vexRT[Ch2]; // The right joystick controls the right back motor

			motor[port6] = vexRT[Ch2]; // The right joystick controls the right front motor


}

}
