#pragma config(Sensor, dgtl1,  Sonar1,         sensorSONAR_mm)
#pragma config(Sensor, dgtl3,  Parallax,       sensorDigitalOut)
#pragma config(Motor,  port1,           relay,         tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           neck,          tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           leftWing,      tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port4,           rightWing,     tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port5,           Legs,          tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           LED,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          Parallax,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void rightNeck ()//.2
{
	setMotor(port2, -20);
	wait(.2);
	stopAllMotors();
}
void leftNeck ()//.2
{
	setMotor(port2, 20);
	wait(.2);
	stopAllMotors();
}
void openWing ()//1
{
	setMotor(port3, 30);
	setMotor(port4, 50);
	wait(1);
	stopAllMotors();

}
void openRightWing()//1
{
	setMotor(port4, 30);
	wait(1);
	stopAllMotors();
}
void openLeftWing()//1
{
	setMotor(port3, 30);
	wait(1);
	stopAllMotors();
}
void closeWings ()
{
	setMotor(port3, -30);
	setMotor(port4, -30);
	wait(1);
	stopAllMotors();
}
void closeRightWing()//1
{
	setMotor(port4, -30);
	wait(1);
	stopAllMotors();
}
void closeLeftWing()//1
{
	setMotor(port3, -30);
	wait(1);
	stopAllMotors();
}
void Flash() //Code block to fade red led's
{wait(.75);setMotor(port9,127);
	wait(.75);setMotor(port9,127);
	wait(.75);setMotor(port9,127);
	wait(.75);setMotor(port9,127);
	wait(.75);setMotor(port9,127);
}
void fastFade() //Code block to fade red led's
{
	wait(.10);setMotor(port9,127);
	wait(.10);setMotor(port9,125);
	wait(.10);setMotor(port9,123);
	wait(.10);setMotor(port9,121);
	wait(.10);setMotor(port9,119);
	wait(.10);setMotor(port9,116);
	wait(.10);setMotor(port9,62);
	wait(.10);setMotor(port9,59);
	wait(.10);setMotor(port9,56);
	wait(.10);setMotor(port9,53);
	wait(.10);setMotor(port9,50);
	wait(.10);setMotor(port9,47);
	wait(.10);setMotor(port9,44);
	wait(.10);setMotor(port9,41);
	wait(.10);setMotor(port9,38);
	wait(.10);setMotor(port9,35);
	wait(.10);setMotor(port9,32);
	wait(.10);setMotor(port9,29);
	wait(.10);setMotor(port9,26);
	wait(.10);setMotor(port9,23);
	wait(.10);setMotor(port9,20);
}
//* Sonar Start *//
task main()
{ setMotor(port9,127);					//Keep lights on
while (1==1)										//Keep the Cortex on while not running code

if ((SensorValue[dgtl1]<=500 && //When sonar is less than 500mm,
		SensorValue[dgtl1]>0) ||		//Even when Sonar reads -1 (power is off) it will not activate, or
		vexRT[Btn8U]==1)						//When remote control is triggered (8U)
{	setMotor(port1,127);					//Activate relay (motor port1)
	Flash();
	wait(3.5);										//Wait 5.5 secs
	setMotor(port10,127);					//Start Parallax Board (Motor Port 10)= logic 1
	wait(3);											//Wait 2 secs
	stopAllMotors();							//Stop All Motors

clearTimer(T1);									//Clear Timer (T1)

	while(time1[T1]<6)						//Until timer reaches 4 secs, run program
		{
		//rightNeck ()//.2
		//leftNeck ()//.2
		//openWing ()//1
		//openRightWing()//1
		//openLeftWing()//1
		//closeWings ()//1
		//closeRightWing()//1
		//closeLeftWing()//1

			fastFade();
			//1:20
			rightNeck ();//.2
			rightNeck ();//.2
			openWing ();//1
			closeWings ();//1
			openLeftWing();//1
			closeLeftWing();//1
			openRightWing();//1
			closeRightWing();//1
			leftNeck ();//.2
			leftNeck ();//.2
			//6.8
			leftNeck ();//.2
			leftNeck ();//.2
			openRightWing();//1
			closeRightWing();//1
			openLeftWing();//1
			closeLeftWing();//1
			openWing ();//1
			closeWings ();//1
			rightNeck ();//.2
			rightNeck ();//.2
			//6.8
			openLeftWing();//1
			closeLeftWing();//1
			leftNeck ();//.2
			leftNeck ();//.2
			rightNeck ();//.2
			rightNeck ();//.2
			openRightWing();//1
			closeRightWing();//1
			openWing ();//1
			closeWings ();//1
			//6.8
			openWing ();//1
			openLeftWing();//1
			closeLeftWing();//1
			leftNeck ();//.2
			leftNeck ();//.2
			rightNeck ();//.2
			rightNeck ();//.2
			openRightWing();//1
			closeRightWing();//1
			closeWings ();//1
			//6.8
			rightNeck ();//.2
			rightNeck ();//.2
			openWing ();//1
			closeWings ();//1
			openLeftWing();//1
			closeLeftWing();//1
			openRightWing();//1
			closeRightWing();//1
			leftNeck ();//.2
			leftNeck ();//.2
			//6.8
			leftNeck ();//.2
			leftNeck ();//.2
			openRightWing();//1
			closeRightWing();//1
			openLeftWing();//1
			closeLeftWing();//1
			openWing ();//1
			closeWings ();//1
			rightNeck ();//.2
			rightNeck ();//.2
			//6.8
			openLeftWing();//1
			closeLeftWing();//1
			leftNeck ();//.2
			leftNeck ();//.2
			rightNeck ();//.2
			rightNeck ();//.2
			openRightWing();//1
			closeRightWing();//1
			openWing ();//1
			closeWings ();//1
			//6.8
			openWing ();//1
			openLeftWing();//1
			closeLeftWing();//1
			leftNeck ();//.2
			leftNeck ();//.2
			rightNeck ();//.2
			rightNeck ();//.2
			openRightWing();//1
			closeRightWing();//1
			closeWings ();//1
			//6.8
			openLeftWing();//1
			closeLeftWing();//1
			leftNeck ();//.2
			leftNeck ();//.2
			rightNeck ();//.2
			rightNeck ();//.2
			openRightWing();//1
			closeRightWing();//1
			openWing ();//1
			closeWings ();//1
			//6.8
			openWing ();//1
			openLeftWing();//1
			closeLeftWing();//1
			leftNeck ();//.2
			leftNeck ();//.2
			rightNeck ();//.2
			rightNeck ();//.2
			openRightWing();//1
			closeRightWing();//1
			closeWings ();//1
			//6.8

			stopAllMotors();					//Stop all Motors
		}
}
}
